### ISSUE TITLE
[enhancement] Use COG as default export format

### ISSUE THREAD

**Issue by Doctor-Who** [EkicierNico/pykic#1]
A Cloud Optimized GeoTIFF (COG) is a regular GeoTIFF file, aimed at being hosted on a HTTP file server, with an internal organization that enables more efficient workflows on the cloud. It does this by leveraging the ability of clients issuing ​HTTP GET range requests to ask for just the parts of a file they need.

Should be interesting to be implemented

**Comment by EkicierNico** [comment]
It's done !
